pool:
  name: default

trigger: none
jobs:
  - job: Build
    steps:
      - task: Docker@2
        inputs:
          command: 'build'
          Dockerfile: '**/Dockerfile'
          tags: 'latest'
          arguments: '-t api'
          