pool:
  name: default

trigger: none
jobs:
  - job: Build
    steps:
      - task: DotNetCoreCLI@2
        displayName: "Restore"
        inputs:
          command: 'restore'
          projects: '**/*.csproj'
          feedsToUse: 'select'
          vstsFeed: 'fa87d356-d9e8-410c-bf26-0078ed3b4646/d6f03ca5-d849-4f99-8de6-b510f6143d44'

      - task: DotNetCoreCLI@2
        displayName: "Build"
        inputs:
          command: 'build'
          projects: '**/*.csproj'

      - task: DotNetCoreCLI@2
        displayName: "Run unit and integration tests"
        inputs:
          command: 'test'
          projects: |
            **/UnitTests.csproj
            **/IntegrationTests.csproj
          arguments: '-c Release --collect:"XPlat Code Coverage"'
          testRunTitle: 'Tests'

      # - task: PowerShell@2
      #   displayName: 'Install code coverage report generator'
      #   inputs:
      #     targetType: 'inline'
      #     script: 'dotnet tool install dotnet-reportgenerator-globaltool -g'

      - task: PowerShell@2
        displayName: 'Generate code coverage report'
        inputs:
          targetType: 'inline'
          script: 'reportgenerator -reports:$(Agent.TempDirectory)/**/coverage.cobertura.xml -targetdir:$(build.sourcesdirectory) -reporttypes:"Cobertura"'

      - task: PublishCodeCoverageResults@1
        displayName: 'Publish code coverage report'
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(build.sourcesdirectory)/Cobertura.xml'

      - task: DotNetCoreCLI@2
        displayName: "Publish api"
        inputs:
          command: 'publish'
          publishWebProjects: true
          arguments: '-c Release -o publish\Api'
          zipAfterPublish: false
          modifyOutputPath: false
          
      # - task: Bash@3
      #   displayName: "Build.ArtifactStagingDirectory to posix path"
      #   inputs:
      #     targetType: 'inline'
      #     script: |
      #       # Convert the path to POSIX format
      #       posix_path=$(echo "$(Build.ArtifactStagingDirectory)" | sed -e 's/\\/\//g' -e 's/:\([^/]\)/\1/g')
      #       echo $posix_path
      #       echo "##vso[task.setvariable variable=linuxposix_path;]$posix_path"


      - task: Docker@2
        displayName: "Create docker image"
        inputs:
          command: 'build'
          Dockerfile: '**/Dockerfile.publish'
          arguments: '-t api --build-arg APP=./publish/Api'

      - task: DotNetCoreCLI@2
        displayName: "Publish functional tests"
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: '**/FunctionalTests.csproj'
          arguments: '-c Release -o $(Build.ArtifactStagingDirectory)\FunctionalTests'

      - task: PublishPipelineArtifact@1
        displayName: "Publish functional tests artifact"
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)\FunctionalTests'
          artifact: 'FunctionalTests'
          publishLocation: 'pipeline'