pool:
  name: default

trigger: none
jobs:
  - job: Build
    steps:
      - task: DotNetCoreCLI@2
        displayName: "Restore"
        inputs:
          command: 'restore'
          projects: '**/*.csproj'
          feedsToUse: 'select'
          vstsFeed: 'fa87d356-d9e8-410c-bf26-0078ed3b4646/d6f03ca5-d849-4f99-8de6-b510f6143d44'
      - task: DotNetCoreCLI@2
        displayName: "Build"
        inputs:
          command: 'build'
          projects: '**/*.csproj'
      - task: DotNetCoreCLI@2
        displayName: "Run unit tests"
        inputs:
          command: 'test'
          projects: '**/UnitTests.csproj'
          arguments: '--collect "Code coverage"'
          testRunTitle: 'Unit tests'
      - task: DotNetCoreCLI@2
        displayName: "Run integration tests"
        inputs:
          command: 'test'
          projects: '**/IntegrationTests.csproj'
          arguments: '--collect "Code coverage"'
          testRunTitle: 'Integration tests'
      - task: DotNetCoreCLI@2
        displayName: "Publish api"
        inputs:
          command: 'publish'
          publishWebProjects: true
          arguments: '-c Release -o $(Build.ArtifactStagingDirectory)\Api'
      # - task: Docker@2
      #   inputs:
      #     command: 'build'
      #     Dockerfile: '**/Dockerfile'
      #     arguments: 'PUBLISH_DIRECTORY=$(Build.ArtifactStagingDirectory)'
      # - task: CopyFiles@2
      #   inputs:
      #     SourceFolder: '**\FunctionalTests\bin\Release\**\'
      #     Contents: '**'
      #     TargetFolder: '$(Build.ArtifactStagingDirectory)\FunctionalTests'
      - task: DotNetCoreCLI@2
        displayName: "Publish functional tests"
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: '**/FunctionalTests.csproj'
          arguments: '-c Release -o $(Build.ArtifactStagingDirectory)\FunctionalTests'
      - task: PublishPipelineArtifact@1
        displayName: "Publish functional tests artifact"
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)\FunctionalTests'
          artifact: 'FunctionalTests'
          publishLocation: 'pipeline'
      - task: Docker@2
        displayName: "Docker build"
        inputs:
          command: 'build'
          Dockerfile: '**/Dockerfile'
          tags: 'latest'
          arguments: '-t api'
      
          