pool:
  name: default

trigger: none
stages:
  - stage: build
    displayName: Build
    jobs:
      - job: BuildAndTests
        displayName: "Build docker image and run tests"
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'GitHub'
              repository: 'michaeltg17'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
          